// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class BookingField
    {
        [Key]
        public long idProduct { get; set; }
        [Key]
        public long idField { get; set; }
        [Required]
        public bool? isShow { get; set; }
        [Required]
        public bool? isMandatory { get; set; }

        [ForeignKey(nameof(idField))]
        [InverseProperty(nameof(Field.BookingField))]
        public virtual Field idFieldNavigation { get; set; }
        [ForeignKey(nameof(idProduct))]
        [InverseProperty(nameof(Product.BookingField))]
        public virtual Product idProductNavigation { get; set; }
    }
}