// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class City
    {
        public City()
        {
            Spot = new HashSet<Spot>();
            SupplierCity = new HashSet<SupplierCity>();
        }

        [Key]
        public long id { get; set; }
        [StringLength(100)]
        public string continent { get; set; }
        [StringLength(100)]
        public string country { get; set; }
        [Required]
        [StringLength(2)]
        public string codeCountry { get; set; }
        [StringLength(100)]
        public string state { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        [StringLength(100)]
        public string nameEN { get; set; }

        [InverseProperty("idCityNavigation")]
        public virtual ICollection<Spot> Spot { get; set; }
        [InverseProperty("idCityNavigation")]
        public virtual ICollection<SupplierCity> SupplierCity { get; set; }
    }
}