// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Extra
    {
        public Extra()
        {
            OrderItemExtra = new HashSet<OrderItemExtra>();
            ProductExtra = new HashSet<ProductExtra>();
        }

        [Key]
        public long id { get; set; }
        public long idSupplier { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        [Required]
        [StringLength(200)]
        public string urlImage { get; set; }
        [Required]
        [StringLength(1000)]
        public string description { get; set; }
        public long price { get; set; }
        public long cost { get; set; }
        [Required]
        [StringLength(4)]
        public string typeOrderQuantity { get; set; }
        [Required]
        public bool? isLimitQuantity { get; set; }
        public short quantityMax { get; set; }
        public short quantityExtra { get; set; }

        [InverseProperty("idExtraNavigation")]
        public virtual ICollection<OrderItemExtra> OrderItemExtra { get; set; }
        [InverseProperty("idExtraNavigation")]
        public virtual ICollection<ProductExtra> ProductExtra { get; set; }
    }
}