// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class MasterCode
    {
        [Key]
        [StringLength(4)]
        public string code { get; set; }
        [Required]
        [StringLength(3)]
        public string typeCode { get; set; }
        [Required]
        [StringLength(3)]
        public string valueCode { get; set; }
        [StringLength(1000)]
        public string desc01 { get; set; }
        [StringLength(1000)]
        public string desc02 { get; set; }
        [StringLength(1000)]
        public string desc03 { get; set; }
    }
}