// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class MessageTemplate
    {
        [Key]
        public long idSupplier { get; set; }
        [StringLength(200)]
        public string fromEmail { get; set; }
        [StringLength(200)]
        public string subject { get; set; }
        [StringLength(4)]
        public string colorTheme { get; set; }
        [Required]
        public bool? isQuickSummary { get; set; }
        [Required]
        public bool? isComplanyLogo { get; set; }
        [StringLength(4)]
        public string headerType { get; set; }
        [StringLength(1000)]
        public string headerValue { get; set; }
        [Required]
        public bool? isOrderSummary { get; set; }
        [Required]
        public bool? isIntroductionText { get; set; }
        public string introductionText { get; set; }
        [Required]
        public bool? isConclusionText { get; set; }
        public string conclusionText { get; set; }
        [Required]
        public bool? isBusinessNumber { get; set; }
        [Required]
        public bool? isCustomerDetail { get; set; }
        [Required]
        public bool? isSpecialRequirement { get; set; }
        [Required]
        public bool? isPaymentDetail { get; set; }
        [StringLength(4)]
        public string typeFooter { get; set; }
        public string footer { get; set; }
        [Required]
        public bool? isItemDetail { get; set; }
        [Required]
        public bool? isQRCode { get; set; }
        [Required]
        public bool? isPickup { get; set; }
        [Required]
        public bool? isMap { get; set; }
        [Required]
        public bool? isItemSummary { get; set; }
        [Required]
        public bool? isGuestDetail { get; set; }
        [Required]
        public bool? isProductSpecialMessage { get; set; }
        [Required]
        public bool? isSpecificTerm { get; set; }
        [Required]
        public bool? isGeneralTerm { get; set; }
        [Required]
        public bool? isCompanyAddress { get; set; }
        [Required]
        public bool? isConnectWithUs { get; set; }
        [Required]
        public bool? isAttachFile { get; set; }

        [ForeignKey(nameof(idSupplier))]
        [InverseProperty(nameof(Supplier.MessageTemplate))]
        public virtual Supplier idSupplierNavigation { get; set; }
    }
}