// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class OrderItemSession
    {
        public OrderItemSession()
        {
            OrderItemResource = new HashSet<OrderItemResource>();
        }

        [Key]
        public long idOrderItem { get; set; }
        [Key]
        public long idSession { get; set; }
        public short quantityUsed { get; set; }
        public long idSpotPickup { get; set; }
        public TimeSpan timePickup { get; set; }
        [Required]
        public bool? isCheckin { get; set; }

        [ForeignKey(nameof(idOrderItem))]
        [InverseProperty(nameof(OrderItem.OrderItemSession))]
        public virtual OrderItem idOrderItemNavigation { get; set; }
        [ForeignKey(nameof(idSession))]
        [InverseProperty(nameof(ProductSession.OrderItemSession))]
        public virtual ProductSession idSessionNavigation { get; set; }
        [InverseProperty("id")]
        public virtual ICollection<OrderItemResource> OrderItemResource { get; set; }
    }
}