// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class OrderItem
    {
        public OrderItem()
        {
            OrderItemExtra = new HashSet<OrderItemExtra>();
            OrderItemField = new HashSet<OrderItemField>();
            OrderItemProduct = new HashSet<OrderItemProduct>();
            OrderItemSession = new HashSet<OrderItemSession>();
        }

        [Key]
        public long id { get; set; }
        public long idOrder { get; set; }
        public long idProduct { get; set; }
        public long idSesstion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetimeFinish { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetimeStart { get; set; }
        public long totalAmount { get; set; }
        public long amountOrder { get; set; }
        public long amountExtra { get; set; }
        public long amountSurcharge { get; set; }
        public long commission { get; set; }
        public short quantityOrder { get; set; }
        public short quantityUsed { get; set; }
        public short quantityExtra { get; set; }
        [Required]
        [StringLength(4)]
        public string typeStatus { get; set; }

        [ForeignKey(nameof(idOrder))]
        [InverseProperty(nameof(Order.OrderItem))]
        public virtual Order idOrderNavigation { get; set; }
        [ForeignKey(nameof(idProduct))]
        [InverseProperty(nameof(Product.OrderItem))]
        public virtual Product idProductNavigation { get; set; }
        [ForeignKey(nameof(idSesstion))]
        [InverseProperty(nameof(ProductSession.OrderItem))]
        public virtual ProductSession idSesstionNavigation { get; set; }
        [InverseProperty("idOrderItemNavigation")]
        public virtual ICollection<OrderItemExtra> OrderItemExtra { get; set; }
        [InverseProperty("idOrderItemNavigation")]
        public virtual ICollection<OrderItemField> OrderItemField { get; set; }
        [InverseProperty("idOrderItemNavigation")]
        public virtual ICollection<OrderItemProduct> OrderItemProduct { get; set; }
        [InverseProperty("idOrderItemNavigation")]
        public virtual ICollection<OrderItemSession> OrderItemSession { get; set; }
    }
}