// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class OrderItemField
    {
        [Key]
        public long id { get; set; }
        public long idOrderItem { get; set; }
        public long idField { get; set; }
        [Required]
        public string valueOrderItem { get; set; }

        [ForeignKey(nameof(idField))]
        [InverseProperty(nameof(Field.OrderItemField))]
        public virtual Field idFieldNavigation { get; set; }
        [ForeignKey(nameof(idOrderItem))]
        [InverseProperty(nameof(OrderItem.OrderItemField))]
        public virtual OrderItem idOrderItemNavigation { get; set; }
    }
}