// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class OrderField
    {
        [Key]
        public long id { get; set; }
        public long idOrder { get; set; }
        public long idField { get; set; }
        [Required]
        public string valueOrder { get; set; }

        [ForeignKey(nameof(idField))]
        [InverseProperty(nameof(Field.OrderField))]
        public virtual Field idFieldNavigation { get; set; }
        [ForeignKey(nameof(idOrder))]
        [InverseProperty(nameof(Order.OrderField))]
        public virtual Order idOrderNavigation { get; set; }
    }
}