// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class OrderItemResource
    {
        [Key]
        public long idOrderItem { get; set; }
        [Key]
        public long idSession { get; set; }
        [Key]
        public long idResource { get; set; }
        public short quantityAssign { get; set; }

        [ForeignKey("idOrderItem,idSession")]
        [InverseProperty(nameof(OrderItemSession.OrderItemResource))]
        public virtual OrderItemSession id { get; set; }
        [ForeignKey("idResource,idSession")]
        [InverseProperty(nameof(SessionResource.OrderItemResource))]
        public virtual SessionResource idNavigation { get; set; }
    }
}