// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class OrderItemProduct
    {
        [Key]
        public long id { get; set; }
        public long idOrderItem { get; set; }
        public long idPrice { get; set; }
        [Required]
        [StringLength(4)]
        public string typePriceOption { get; set; }
        public long price { get; set; }
        public short quantityOrder { get; set; }
        public short quantityUnit { get; set; }
        public long amountOrder { get; set; }
        public short quantityUsed { get; set; }

        [ForeignKey(nameof(idOrderItem))]
        [InverseProperty(nameof(OrderItem.OrderItemProduct))]
        public virtual OrderItem idOrderItemNavigation { get; set; }
        [ForeignKey(nameof(idPrice))]
        [InverseProperty(nameof(ProductPrice.OrderItemProduct))]
        public virtual ProductPrice idPriceNavigation { get; set; }
    }
}