// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderField = new HashSet<OrderField>();
            OrderItem = new HashSet<OrderItem>();
            PaymentOrder = new HashSet<PaymentOrder>();
        }

        [Key]
        public long id { get; set; }
        [Required]
        [StringLength(4)]
        public string typeOrder { get; set; }
        [Required]
        [StringLength(4)]
        public string typeCustomer { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetimeCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetimeConfirmed { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetimePaid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetimeUpdated { get; set; }
        public long totalSale { get; set; }
        public long totalOrder { get; set; }
        public long totalPaid { get; set; }
        public long totalDue { get; set; }
        public long totalDiscount { get; set; }
        [Required]
        public bool? isFullpay { get; set; }
        [Required]
        public bool? isSendCheckin { get; set; }
        [Required]
        public bool? isSendPayment { get; set; }
        [Required]
        public string listTypePayment { get; set; }
        [Required]
        [StringLength(4)]
        public string typeSource { get; set; }
        [StringLength(1000)]
        public string refererSource { get; set; }
        [StringLength(2000)]
        public string commentCustomer { get; set; }
        [StringLength(2000)]
        public string commentAgent { get; set; }
        [StringLength(2000)]
        public string commentSupplier { get; set; }
        [StringLength(2000)]
        public string commentTripBox { get; set; }

        [InverseProperty("idOrderNavigation")]
        public virtual ICollection<OrderField> OrderField { get; set; }
        [InverseProperty("idOrderNavigation")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        [InverseProperty("idOrderNavigation")]
        public virtual ICollection<PaymentOrder> PaymentOrder { get; set; }
    }
}