// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class OrderItemExtra
    {
        [Key]
        public long id { get; set; }
        public long idOrderItem { get; set; }
        public long idExtra { get; set; }
        public long priceExtra { get; set; }
        public short quantityExtra { get; set; }
        public long amountExtra { get; set; }

        [ForeignKey(nameof(idExtra))]
        [InverseProperty(nameof(Extra.OrderItemExtra))]
        public virtual Extra idExtraNavigation { get; set; }
        [ForeignKey(nameof(idOrderItem))]
        [InverseProperty(nameof(OrderItem.OrderItemExtra))]
        public virtual OrderItem idOrderItemNavigation { get; set; }
    }
}