// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class PackageSession
    {
        [Key]
        public long idProduct { get; set; }
        [Key]
        public long idProductPart { get; set; }
        [Key]
        public long idSessionPart { get; set; }

        [ForeignKey("idProduct,idProductPart")]
        [InverseProperty(nameof(Package.PackageSession))]
        public virtual Package idProductNavigation { get; set; }
        [ForeignKey(nameof(idSessionPart))]
        [InverseProperty(nameof(ProductSession.PackageSession))]
        public virtual ProductSession idSessionPartNavigation { get; set; }
    }
}