// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Package
    {
        public Package()
        {
            PackageSession = new HashSet<PackageSession>();
        }

        [Key]
        public long idProduct { get; set; }
        [Key]
        public long idProductPart { get; set; }
        [Required]
        [StringLength(4)]
        public string typeProduct { get; set; }
        public short day { get; set; }
        [Required]
        public bool? isAllday { get; set; }
        public TimeSpan timeStart { get; set; }
        public TimeSpan timeFinish { get; set; }

        [ForeignKey(nameof(idProduct))]
        [InverseProperty(nameof(Product.PackageidProductNavigation))]
        public virtual Product idProductNavigation { get; set; }
        [ForeignKey(nameof(idProductPart))]
        [InverseProperty(nameof(Product.PackageidProductPartNavigation))]
        public virtual Product idProductPartNavigation { get; set; }
        [InverseProperty("idProductNavigation")]
        public virtual ICollection<PackageSession> PackageSession { get; set; }
    }
}