// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class PartyAccount
    {
        [Key]
        public long id { get; set; }
        public long idPartyHolder { get; set; }
        [Required]
        [StringLength(4)]
        public string typeAccount { get; set; }
        [Required]
        [StringLength(4)]
        public string typeFinance { get; set; }
        public long idPartyFinance { get; set; }
        [Required]
        [StringLength(20)]
        public string accountNo { get; set; }
        [Required]
        [StringLength(20)]
        public string accountName { get; set; }

        [ForeignKey(nameof(idPartyHolder))]
        [InverseProperty(nameof(Party.PartyAccount))]
        public virtual Party idPartyHolderNavigation { get; set; }
    }
}