// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class PartyRelation
    {
        [Key]
        public long idParty1 { get; set; }
        [Key]
        public long idParty2 { get; set; }
        [Key]
        [StringLength(4)]
        public string typeRelation { get; set; }

        [ForeignKey(nameof(idParty1))]
        [InverseProperty(nameof(Party.PartyRelationidParty1Navigation))]
        public virtual Party idParty1Navigation { get; set; }
        [ForeignKey(nameof(idParty2))]
        [InverseProperty(nameof(Party.PartyRelationidParty2Navigation))]
        public virtual Party idParty2Navigation { get; set; }
    }
}