// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Party
    {
        public Party()
        {
            PartyAccount = new HashSet<PartyAccount>();
            PartyContact = new HashSet<PartyContact>();
            PartyRelationidParty1Navigation = new HashSet<PartyRelation>();
            PartyRelationidParty2Navigation = new HashSet<PartyRelation>();
            Purchage = new HashSet<Purchage>();
            SessionRole = new HashSet<SessionRole>();
        }

        [Key]
        public long id { get; set; }
        [Required]
        [StringLength(4)]
        public string typeParty { get; set; }
        [StringLength(100)]
        public string nameFirst { get; set; }
        [StringLength(100)]
        public string nameLast { get; set; }
        [StringLength(100)]
        public string nameCompany { get; set; }
        [StringLength(100)]
        public string companyAlias { get; set; }
        [StringLength(4)]
        public string gender { get; set; }
        [StringLength(100)]
        public string title { get; set; }
        [Column(TypeName = "date")]
        public DateTime? dateBirth { get; set; }

        [InverseProperty("idAgentNavigation")]
        public virtual Agent Agent { get; set; }
        [InverseProperty("idPartyNavigation")]
        public virtual Member Member { get; set; }
        [InverseProperty("idSupplierNavigation")]
        public virtual Supplier Supplier { get; set; }
        [InverseProperty("idPartyHolderNavigation")]
        public virtual ICollection<PartyAccount> PartyAccount { get; set; }
        [InverseProperty("idPartyNavigation")]
        public virtual ICollection<PartyContact> PartyContact { get; set; }
        [InverseProperty(nameof(PartyRelation.idParty1Navigation))]
        public virtual ICollection<PartyRelation> PartyRelationidParty1Navigation { get; set; }
        [InverseProperty(nameof(PartyRelation.idParty2Navigation))]
        public virtual ICollection<PartyRelation> PartyRelationidParty2Navigation { get; set; }
        [InverseProperty("idCompanyPurchaseNavigation")]
        public virtual ICollection<Purchage> Purchage { get; set; }
        [InverseProperty("idPartyNavigation")]
        public virtual ICollection<SessionRole> SessionRole { get; set; }
    }
}