// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Payment
    {
        public Payment()
        {
            PaymentOrder = new HashSet<PaymentOrder>();
        }

        [Key]
        public long id { get; set; }
        [Required]
        [StringLength(4)]
        public string typePayment { get; set; }
        [Required]
        [StringLength(4)]
        public string typeReceipt { get; set; }
        [Column(TypeName = "date")]
        public DateTime datePayment { get; set; }
        public long amount { get; set; }
        [StringLength(1000)]
        public string note { get; set; }

        [InverseProperty("idPaymentNavigation")]
        public virtual ICollection<PaymentOrder> PaymentOrder { get; set; }
    }
}