// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class PaymentOrder
    {
        [Key]
        public long id { get; set; }
        public long idPayment { get; set; }
        public long idOrder { get; set; }
        public long amount { get; set; }

        [ForeignKey(nameof(idOrder))]
        [InverseProperty(nameof(Order.PaymentOrder))]
        public virtual Order idOrderNavigation { get; set; }
        [ForeignKey(nameof(idPayment))]
        [InverseProperty(nameof(Payment.PaymentOrder))]
        public virtual Payment idPaymentNavigation { get; set; }
    }
}