// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Pickup
    {
        public Pickup()
        {
            PickupSpot = new HashSet<PickupSpot>();
            Product = new HashSet<Product>();
        }

        [Key]
        public long id { get; set; }
        public long idSupplier { get; set; }
        [Required]
        [StringLength(100)]
        public string name { get; set; }
        [Required]
        public bool? isAllowRequest { get; set; }
        [StringLength(1000)]
        public string noteRequest { get; set; }
        [Required]
        public bool? isAdditionalNote { get; set; }
        [StringLength(1000)]
        public string noteAdditional { get; set; }
        public long? idSpotStart { get; set; }
        public long? idSpotEnd { get; set; }
        public short miniteDuration { get; set; }

        [InverseProperty("idPickupNavigation")]
        public virtual ICollection<PickupSpot> PickupSpot { get; set; }
        [InverseProperty("idPickupNavigation")]
        public virtual ICollection<Product> Product { get; set; }
    }
}