// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class PickupSpot
    {
        [Key]
        public long idPickup { get; set; }
        [Key]
        public long idSpot { get; set; }
        public short seq { get; set; }
        [Required]
        [StringLength(100)]
        public string name { get; set; }
        public short minutePrior { get; set; }
        [StringLength(1000)]
        public string noteInstruction { get; set; }

        [ForeignKey(nameof(idPickup))]
        [InverseProperty(nameof(Pickup.PickupSpot))]
        public virtual Pickup idPickupNavigation { get; set; }
        [ForeignKey(nameof(idSpot))]
        [InverseProperty(nameof(Spot.PickupSpot))]
        public virtual Spot idSpotNavigation { get; set; }
    }
}