// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class PriceOption
    {
        [Key]
        public long idProduct { get; set; }
        [Key]
        [StringLength(4)]
        public string typePriceOption { get; set; }
        [Required]
        public bool? isGroup { get; set; }
        public short quantitytUnit { get; set; }
        public long price { get; set; }
        public long cost { get; set; }
        public short quantityMax { get; set; }
        public long? idResource { get; set; }
        [Required]
        [StringLength(1000)]
        public string note { get; set; }
        [Column(TypeName = "numeric(12, 2)")]
        public decimal rateMarketplace { get; set; }

        [ForeignKey(nameof(idProduct))]
        [InverseProperty(nameof(Product.PriceOption))]
        public virtual Product idProductNavigation { get; set; }
        [ForeignKey(nameof(idResource))]
        [InverseProperty(nameof(Resource.PriceOption))]
        public virtual Resource idResourceNavigation { get; set; }
    }
}