// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class ProductSurcharge
    {
        [Key]
        public long idProduct { get; set; }
        public long idSurcharge { get; set; }
        public short seq { get; set; }

        [ForeignKey(nameof(idProduct))]
        [InverseProperty(nameof(Product.ProductSurcharge))]
        public virtual Product idProductNavigation { get; set; }
        [ForeignKey(nameof(idSurcharge))]
        [InverseProperty(nameof(Surcharge.ProductSurcharge))]
        public virtual Surcharge idSurchargeNavigation { get; set; }
    }
}