// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class ProductImage
    {
        [Key]
        public long id { get; set; }
        public long idProduct { get; set; }
        public short seq { get; set; }
        [Required]
        public bool? isDefault { get; set; }
        [Required]
        [StringLength(200)]
        public string urlImageFull { get; set; }
        [Required]
        [StringLength(200)]
        public string urlImageLarge { get; set; }
        [Required]
        [StringLength(200)]
        public string urlImageMedium { get; set; }
        [Required]
        [StringLength(200)]
        public string urlImageSmall { get; set; }

        [ForeignKey(nameof(idProduct))]
        [InverseProperty(nameof(Product.ProductImage))]
        public virtual Product idProductNavigation { get; set; }
    }
}