// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class ProductExtra
    {
        [Key]
        public long idProduct { get; set; }
        [Key]
        public long idExtra { get; set; }
        public short seq { get; set; }

        [ForeignKey(nameof(idExtra))]
        [InverseProperty(nameof(Extra.ProductExtra))]
        public virtual Extra idExtraNavigation { get; set; }
        [ForeignKey(nameof(idProduct))]
        [InverseProperty(nameof(Product.ProductExtra))]
        public virtual Product idProductNavigation { get; set; }
    }
}