// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class ProductSession
    {
        public ProductSession()
        {
            OrderItem = new HashSet<OrderItem>();
            OrderItemSession = new HashSet<OrderItemSession>();
            PackageSession = new HashSet<PackageSession>();
            ProductPrice = new HashSet<ProductPrice>();
            SessionResource = new HashSet<SessionResource>();
        }

        [Key]
        public long id { get; set; }
        public long idTemplate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetimeStart { get; set; }
        [Required]
        public bool? isAllday { get; set; }
        [StringLength(4)]
        public string timetypeDuration { get; set; }
        public short valueDuration { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetimeFinish { get; set; }
        public short quantityMax { get; set; }
        public short quantityUsed { get; set; }

        [ForeignKey(nameof(idTemplate))]
        [InverseProperty(nameof(SessionTemplate.ProductSession))]
        public virtual SessionTemplate idTemplateNavigation { get; set; }
        [InverseProperty("idSesstionNavigation")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        [InverseProperty("idSessionNavigation")]
        public virtual ICollection<OrderItemSession> OrderItemSession { get; set; }
        [InverseProperty("idSessionPartNavigation")]
        public virtual ICollection<PackageSession> PackageSession { get; set; }
        [InverseProperty("idSessionNavigation")]
        public virtual ICollection<ProductPrice> ProductPrice { get; set; }
        [InverseProperty("idSessionNavigation")]
        public virtual ICollection<SessionResource> SessionResource { get; set; }
    }
}