// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class ProductVideo
    {
        [Key]
        public long id { get; set; }
        public long idProduct { get; set; }
        public short seq { get; set; }
        [Required]
        public bool? isDefault { get; set; }
        [Required]
        [StringLength(4)]
        public string typePlatform { get; set; }
        [Required]
        [StringLength(200)]
        public string urlVideo { get; set; }

        [ForeignKey(nameof(idProduct))]
        [InverseProperty(nameof(Product.ProductVideo))]
        public virtual Product idProductNavigation { get; set; }
    }
}