// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class ProductPrice
    {
        public ProductPrice()
        {
            OrderItemProduct = new HashSet<OrderItemProduct>();
        }

        [Key]
        public long id { get; set; }
        public long idProduct { get; set; }
        [Required]
        [StringLength(4)]
        public string typePriceOption { get; set; }
        public long? idSession { get; set; }
        public long price { get; set; }
        public long cost { get; set; }
        public short quantityMax { get; set; }
        public short quantityOrder { get; set; }

        [ForeignKey(nameof(idSession))]
        [InverseProperty(nameof(ProductSession.ProductPrice))]
        public virtual ProductSession idSessionNavigation { get; set; }
        [InverseProperty("idPriceNavigation")]
        public virtual ICollection<OrderItemProduct> OrderItemProduct { get; set; }
    }
}