// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class ProductSpot
    {
        [Key]
        public long idProduct { get; set; }
        [Key]
        public short seq { get; set; }
        [Key]
        public long idSpot { get; set; }
        [StringLength(4)]
        public string typeService { get; set; }

        [ForeignKey(nameof(idProduct))]
        [InverseProperty(nameof(Product.ProductSpot))]
        public virtual Product idProductNavigation { get; set; }
        [ForeignKey(nameof(idSpot))]
        [InverseProperty(nameof(Spot.ProductSpot))]
        public virtual Spot idSpotNavigation { get; set; }
    }
}