// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class ProductRelated
    {
        [Key]
        public long idProduct1 { get; set; }
        [Key]
        public long idProduct2 { get; set; }

        [ForeignKey(nameof(idProduct1))]
        [InverseProperty(nameof(Product.ProductRelatedidProduct1Navigation))]
        public virtual Product idProduct1Navigation { get; set; }
        [ForeignKey(nameof(idProduct2))]
        [InverseProperty(nameof(Product.ProductRelatedidProduct2Navigation))]
        public virtual Product idProduct2Navigation { get; set; }
    }
}