// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Promotion
    {
        [Key]
        [StringLength(10)]
        public string codePromotion { get; set; }
        [Column(TypeName = "date")]
        public DateTime dateOrderStart { get; set; }
        [Column(TypeName = "date")]
        public DateTime dateOrderEnd { get; set; }
        [Column(TypeName = "date")]
        public DateTime dateSessionStart { get; set; }
        [Column(TypeName = "date")]
        public DateTime dateSessionEnd { get; set; }
        [StringLength(4)]
        public string typeApply { get; set; }
        [Column(TypeName = "numeric(12, 2)")]
        public decimal ratePromotion { get; set; }
        [Required]
        public bool? isLimitTotal { get; set; }
        public long amountLimit { get; set; }
        public long amountMin { get; set; }
        [Required]
        public bool? isIncludeSurcharge { get; set; }
        [Required]
        public bool? isIncludeExtra { get; set; }
        [StringLength(4)]
        public string typeApplyProduct { get; set; }
        public long? idProduct { get; set; }
        public long? idCategory { get; set; }

        [ForeignKey(nameof(idProduct))]
        [InverseProperty(nameof(Product.Promotion))]
        public virtual Product idProductNavigation { get; set; }
    }
}