// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Purchage
    {
        public Purchage()
        {
            PurchageDetail = new HashSet<PurchageDetail>();
        }

        [Key]
        public long id { get; set; }
        public long idSupplier { get; set; }
        [Column(TypeName = "date")]
        public DateTime datePurchage { get; set; }
        public long? idCompanyPurchase { get; set; }
        [StringLength(100)]
        public string companyPurchage { get; set; }
        public long totalPurchage { get; set; }
        [StringLength(1000)]
        public string note { get; set; }

        [ForeignKey(nameof(idCompanyPurchase))]
        [InverseProperty(nameof(Party.Purchage))]
        public virtual Party idCompanyPurchaseNavigation { get; set; }
        [InverseProperty("idPurchageNavigation")]
        public virtual ICollection<PurchageDetail> PurchageDetail { get; set; }
    }
}