// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class PurchageDetail
    {
        [Key]
        public long id { get; set; }
        public long idPurchage { get; set; }
        public long idSession { get; set; }
        [Required]
        [StringLength(4)]
        public string typeItem { get; set; }
        [Required]
        [StringLength(4)]
        public string typePayment { get; set; }
        public long cost { get; set; }
        public short quantityPurchage { get; set; }
        public long amountPurchage { get; set; }
        [StringLength(1000)]
        public string note { get; set; }

        [ForeignKey(nameof(idPurchage))]
        [InverseProperty(nameof(Purchage.PurchageDetail))]
        public virtual Purchage idPurchageNavigation { get; set; }
        [ForeignKey(nameof(idSession))]
        [InverseProperty(nameof(SessionOrdered.PurchageDetail))]
        public virtual SessionOrdered idSessionNavigation { get; set; }
    }
}