// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Resource
    {
        public Resource()
        {
            PriceOption = new HashSet<PriceOption>();
            SessionResource = new HashSet<SessionResource>();
        }

        [Key]
        public long id { get; set; }
        public long idSupplier { get; set; }
        [Required]
        [StringLength(100)]
        public string name { get; set; }
        [Required]
        [StringLength(4)]
        public string typeResource { get; set; }
        [Required]
        public bool? isLimitQuantity { get; set; }
        public short quantityMax { get; set; }
        [Required]
        [StringLength(4)]
        public string typeShace { get; set; }

        [InverseProperty("idResourceNavigation")]
        public virtual ICollection<PriceOption> PriceOption { get; set; }
        [InverseProperty("idResourceNavigation")]
        public virtual ICollection<SessionResource> SessionResource { get; set; }
    }
}