// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class SessionOrdered
    {
        public SessionOrdered()
        {
            PurchageDetail = new HashSet<PurchageDetail>();
            SessionRole = new HashSet<SessionRole>();
        }

        [Key]
        public long idSessionPart { get; set; }
        public long idProduct { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetimeStart { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetimeFinish { get; set; }
        public long amountProfit { get; set; }
        public long amountSale { get; set; }
        public long commAgent { get; set; }
        public long commOperation { get; set; }
        public long amountExpense { get; set; }
        public short quantityUsed { get; set; }

        [InverseProperty("idSessionNavigation")]
        public virtual ICollection<PurchageDetail> PurchageDetail { get; set; }
        [InverseProperty("idSessionPartNavigation")]
        public virtual ICollection<SessionRole> SessionRole { get; set; }
    }
}