// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class SessionTemplateWeek
    {
        [Key]
        public long idTemplate { get; set; }
        [Key]
        public short weekdayNo { get; set; }
        public TimeSpan timeStart { get; set; }
        public TimeSpan timeEnd { get; set; }

        [ForeignKey(nameof(idTemplate))]
        [InverseProperty(nameof(SessionTemplate.SessionTemplateWeek))]
        public virtual SessionTemplate idTemplateNavigation { get; set; }
    }
}