// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class SessionRole
    {
        [Key]
        public long id { get; set; }
        public long idSessionPart { get; set; }
        [Required]
        [StringLength(4)]
        public string typeRole { get; set; }
        public long idParty { get; set; }

        [ForeignKey(nameof(idParty))]
        [InverseProperty(nameof(Party.SessionRole))]
        public virtual Party idPartyNavigation { get; set; }
        [ForeignKey(nameof(idSessionPart))]
        [InverseProperty(nameof(SessionOrdered.SessionRole))]
        public virtual SessionOrdered idSessionPartNavigation { get; set; }
    }
}