// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Spot
    {
        public Spot()
        {
            PickupSpot = new HashSet<PickupSpot>();
            ProductSpot = new HashSet<ProductSpot>();
        }

        [Key]
        public long id { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        [Required]
        [StringLength(4)]
        public string typeSpot { get; set; }
        public long idCity { get; set; }
        [StringLength(10)]
        public string postcode { get; set; }
        [StringLength(100)]
        public string address1 { get; set; }
        [StringLength(100)]
        public string address2 { get; set; }
        [Required]
        [StringLength(20)]
        public string latitude { get; set; }
        [Required]
        [StringLength(20)]
        public string longitude { get; set; }

        [ForeignKey(nameof(idCity))]
        [InverseProperty(nameof(City.Spot))]
        public virtual City idCityNavigation { get; set; }
        [InverseProperty("idSpotNavigation")]
        public virtual ICollection<PickupSpot> PickupSpot { get; set; }
        [InverseProperty("idSpotNavigation")]
        public virtual ICollection<ProductSpot> ProductSpot { get; set; }
    }
}