// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class Surcharge
    {
        public Surcharge()
        {
            ProductSurcharge = new HashSet<ProductSurcharge>();
        }

        [Key]
        public long id { get; set; }
        public long idSupplier { get; set; }
        [Required]
        [StringLength(20)]
        public string label { get; set; }
        [Required]
        [StringLength(4)]
        public string typeSurcharge { get; set; }
        [Required]
        [StringLength(4)]
        public string typeApply { get; set; }
        [Column(TypeName = "numeric(12, 2)")]
        public decimal rateSurcharge { get; set; }
        [StringLength(1000)]
        public string note { get; set; }

        [ForeignKey(nameof(idSupplier))]
        [InverseProperty(nameof(Supplier.Surcharge))]
        public virtual Supplier idSupplierNavigation { get; set; }
        [InverseProperty("idSurchargeNavigation")]
        public virtual ICollection<ProductSurcharge> ProductSurcharge { get; set; }
    }
}