// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models
{
    public partial class User
    {
        [Key]
        public long idSupplier { get; set; }
        [Key]
        public long idParty { get; set; }
        [StringLength(4)]
        public string typeRole { get; set; }
        [Required]
        public bool? isOrderOnline { get; set; }
        [Required]
        public bool? isOrderInternal { get; set; }
        [Required]
        public bool? isNewCompany { get; set; }
        [Required]
        public bool? isMessage { get; set; }
        [Required]
        public bool? isViewCompany { get; set; }
        [Required]
        public bool? isWeeklyReport { get; set; }
        [Required]
        public bool? isAbandonCart { get; set; }
        [Required]
        public bool? isBouncedEmail { get; set; }

        [ForeignKey(nameof(idParty))]
        [InverseProperty(nameof(Member.User))]
        public virtual Member idPartyNavigation { get; set; }
        [ForeignKey(nameof(idSupplier))]
        [InverseProperty(nameof(Supplier.User))]
        public virtual Supplier idSupplierNavigation { get; set; }
    }
}